### ISSUE TITLE
Smart groups display 0 contacts

### ISSUE THREAD

**Issue by badlard** [praekeltfoundation/vumi-go#621] opened 2013-08-15 10:11 UTC
On the smart groups page: https://go.vumi.org/contacts/groups/smart/
- In the first screen shot, see that the number of contacts for each smart group is '0'
- in the second screen shot, see that the actual number of contacts in the smart group "Unfamiliar" is '7'
- the number '7' should therefore be displayed on the smart groups page

![screen shot 2013-08-15 at 12 08 16 pm](https://f.cloud.github.com/assets/1521387/968086/dae8bab4-0592-11e3-89cc-af31c320e8aa.png)

![screen shot 2013-08-15 at 12 08 25 pm](https://f.cloud.github.com/assets/1521387/968087/edbfa166-0592-11e3-8fd3-68484600d475.png)

**Comment by smn** [comment] 2013-08-15 10:17
Duplicate of #614, closing that one because this one has screenshots.
Just remember that #137 is around to address this kind of stuff. Counting stuff in Riak is expensive.

**Comment by justinvdm** [comment] 2013-08-15 13:54
Solved in #618

**Closed as completed by justinvdm** 2013-08-15 13:54 UTC
Labels: Bug
