### ISSUE TITLE
Switching to outbound message on conversation triggers HTTP 500

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/vumi-go#693] opened 2013-09-06 07:08 UTC
Conversation type: jsbox

![screen shot 2013-09-06 at 9 05 45 am](https://f.cloud.github.com/assets/1228977/1094235/12e3ad34-16c3-11e3-9aae-d2788f911bbf.png)

**Comment by hodgestar** [comment] 2013-09-06 07:48
Duplicate of #675.

**Closed as completed by hodgestar** 2013-09-06 07:48 UTC
