### ISSUE TITLE
Cannot page through contacts in the Go UI

### ISSUE THREAD

**Issue by vgeddes** [praekeltfoundation/vumi-go#828] opened 2013-12-20 03:18 UTC
The Go UI only shows the first 100 contacts, and doesn't provide controls to page through the rest.

**Comment by smn** [comment] 2013-12-20 04:16
Related https://github.com/praekelt/vumi-go/pull/137.

**Comment by hodgestar** [comment] 2013-12-20 07:10
This is a duplicate of #677.

**Closed as completed by hodgestar** 2013-12-20 07:10 UTC
Labels: UI, Bug
